//===----------------------------------------------------------------------===//
//
// Part of Silicon, licensed under the Apache License v2.0 with LLVM Exceptions.
// See the LICENSE file for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "silicon/Codegen/Codegen.h"
#include "silicon/Conversion/Passes.h"
#include "silicon/HIR/Passes.h"
#include "silicon/RegisterAll.h"
#include "silicon/Support/MLIR.h"
#include "silicon/Syntax/AST.h"
#include "silicon/Syntax/Lexer.h"
#include "silicon/Syntax/Names.h"
#include "silicon/Syntax/Parser.h"
#include "silicon/Transforms/Passes.h"
#include "mlir/Bytecode/BytecodeReader.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/OwningOpRef.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/ToolUtilities.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/WithColor.h"

using namespace silicon;
namespace cl = llvm::cl;

//===----------------------------------------------------------------------===//
// Command Line Options
//===----------------------------------------------------------------------===//

enum class LoweringMode { Parse, HIR, MIR, HW };
enum class Format { Silicon, MLIR };

struct Opt {
  cl::opt<std::string> inputFilename{cl::Positional, cl::init("-"),
                                     cl::desc("[input]")};

  cl::opt<std::string> outputFilename{
      "o", cl::value_desc("filename"), cl::init("-"),
      cl::desc("Output filename (`-` for stdout)")};

  cl::opt<bool> verifyDiagnostics{
      "verify-diagnostics", cl::init(false), cl::Hidden,
      cl::desc("Check that emitted diagnostics match expected-* lines on the "
               "corresponding line")};

  cl::opt<bool> testLexer{"test-lexer", cl::init(false), cl::Hidden,
                          cl::desc("Print all tokens in the input")};

  cl::opt<bool> testParser{"test-parser", cl::init(false), cl::Hidden,
                           cl::desc("Print the AST after parsing")};

  cl::opt<bool> splitInputFile{
      "split-input-file", cl::init(false), cl::Hidden,
      cl::desc("Split the input file into chunks and process each separately")};

  cl::opt<LoweringMode> loweringMode{
      cl::desc("Specify how to process the input:"),
      cl::values(clEnumValN(LoweringMode::Parse, "parse-only",
                            "Emit the IR immediately after parsing"),
                 clEnumValN(LoweringMode::HIR, "ir-hir",
                            "Stop after split-phases (HIR level)"),
                 clEnumValN(LoweringMode::MIR, "ir-mir",
                            "Stop after phase evaluation (MIR level)"),
                 clEnumValN(LoweringMode::HW, "ir-hw",
                            "Full pipeline including CIRCT lowering")),
      cl::init(LoweringMode::HW)};

  cl::opt<Format> format{
      "format",
      cl::desc("Input file format (auto-detected from extension by default)"),
      cl::values(
          clEnumValN(Format::Silicon, "silicon",
                     "Parse as Silicon source text"),
          clEnumValN(Format::MLIR, "mlir", "Parse as MLIR or MLIRBC file"))};
};
static Opt opt;

//===----------------------------------------------------------------------===//
// Pass Pipeline
//===----------------------------------------------------------------------===//

/// Add canonicalization and CSE cleanup passes.
static void addCleanup(PassManager &pm) {
  auto &anyPM = pm.nestAny();
  anyPM.addPass(mlir::createCanonicalizerPass());
  anyPM.addPass(mlir::createCSEPass());
}

static void populatePasses(PassManager &pm) {
  // Perform an initial cleanup after parsing.
  addCleanup(pm);

  // Check function calls against their function signatures.
  pm.addPass(hir::createCheckCallsPass());
  {
    auto &anyPM = pm.nestAny();
    // Do an initial canonicalization pass to help resolve the `hir.type_of` ops
    // generated by the CheckCalls pass.
    anyPM.addPass(mlir::createCanonicalizerPass());
    anyPM.addPass(mlir::createCSEPass());
    anyPM.addPass(mlir::createCanonicalizerPass());
  }

  // Infer types throughout the IR.
  pm.addPass(hir::createInferTypesPass());
  addCleanup(pm);

  // Split functions into phases based on constness.
  pm.addPass(hir::createSplitPhasesPass());
  addCleanup(pm);

  if (opt.loweringMode == LoweringMode::HIR)
    return;

  // Iteratively lower, interpret, and specialize until all compile-time phases
  // are evaluated.
  pm.addPass(createPhaseEvalLoopPass());
  addCleanup(pm);

  if (opt.loweringMode == LoweringMode::MIR)
    return;

  // Lower module call graphs to CIRCT hw/comb, erase all remaining Silicon
  // dialect ops.
  pm.addPass(createMIRToCIRCTPass());
  addCleanup(pm);
}

//===----------------------------------------------------------------------===//
// Driver
//===----------------------------------------------------------------------===//

/// Detect whether the input should be parsed as Silicon source or MLIR,
/// based on the `--format` flag if given, or on the file extension and
/// bytecode magic otherwise.
static Format detectFormat(llvm::StringRef filename,
                           const llvm::MemoryBuffer &buf) {
  if (opt.format.getNumOccurrences() > 0)
    return opt.format;
  if (filename.ends_with(".mlir") || filename.ends_with(".mlirbc") ||
      mlir::isBytecode(buf.getMemBufferRef()))
    return Format::MLIR;
  return Format::Silicon;
}

/// Parse a Silicon source file through the lexer, parser, name resolver, and
/// codegen pipeline.
///
/// Returns `failure()` on error. Returns `success({})` (a null module) when an
/// early-exit option like `--test-lexer` or `--test-parser` already printed its
/// output. Returns `success(module)` when a module is ready for further
/// processing.
static FailureOr<mlir::OwningOpRef<mlir::ModuleOp>>
parseSilicon(MLIRContext *context, llvm::SourceMgr &sourceMgr,
             llvm::raw_ostream &os) {
  Lexer lexer(context, sourceMgr);

  // If we are only testing the lexer, print all tokens and exit early.
  if (opt.testLexer) {
    while (auto token = lexer.next()) {
      if (token.isError())
        return failure();
      os << lexer.getLoc(token) << ": " << token << "\n";
    }
    return mlir::OwningOpRef<mlir::ModuleOp>{};
  }

  // Parse the input into an AST and resolve names.
  AST ast;
  Parser parser(lexer, ast);
  auto *root = parser.parseRoot();
  if (!root)
    return failure();
  ast.roots.push_back(root);
  if (failed(resolveNames(ast)))
    return failure();

  // If we are only testing the parser, print the AST and exit early.
  if (opt.testParser) {
    ast.print(os);
    return mlir::OwningOpRef<mlir::ModuleOp>{};
  }

  // Convert the AST to MLIR.
  auto module = convertToIR(context, ast);
  if (!module)
    return failure();
  return module;
}

/// Parse an MLIR text or bytecode file.
///
/// Returns `failure()` if parsing fails, `success(module)` otherwise.
static FailureOr<mlir::OwningOpRef<mlir::ModuleOp>>
parseMlir(MLIRContext *context, llvm::SourceMgr &sourceMgr) {
  mlir::ParserConfig config(context);
  auto module = mlir::parseSourceFile<mlir::ModuleOp>(sourceMgr, config);
  if (!module)
    return failure();
  return module;
}

/// Detect the format, parse the input, run the pass pipeline, and emit MLIR.
static LogicalResult process(MLIRContext *context, llvm::SourceMgr &sourceMgr,
                             llvm::raw_ostream &os) {
  // Detect the format and parse into a module.
  auto *buf = sourceMgr.getMemoryBuffer(sourceMgr.getMainFileID());
  FailureOr<mlir::OwningOpRef<mlir::ModuleOp>> moduleOrErr;
  if (detectFormat(opt.inputFilename, *buf) == Format::MLIR)
    moduleOrErr = parseMlir(context, sourceMgr);
  else
    moduleOrErr = parseSilicon(context, sourceMgr, os);

  if (failed(moduleOrErr))
    return failure();
  auto &module = *moduleOrErr;
  if (!module)
    return success(); // early exit for --test-lexer / --test-parser

  // If the user requested anything besides simply parsing the input, run the
  // appropriate transformation passes according to the command line options.
  if (opt.loweringMode != LoweringMode::Parse) {
    PassManager pm(context);
    pm.enableVerifier(true);
    if (failed(applyPassManagerCLOptions(pm)))
      return failure();
    populatePasses(pm);
    if (failed(pm.run(*module)))
      return failure();
  }

  // Print the final MLIR.
  module->print(os);
  return success();
}

static LogicalResult executeCompiler(MLIRContext *context) {
  // Open the source file.
  std::string errorMessage;
  auto inputFile = mlir::openInputFile(opt.inputFilename, &errorMessage);
  if (!inputFile) {
    llvm::WithColor::error()
        << "failed to open input file: " << errorMessage << "\n";
    return failure();
  }

  // Open the output file.
  auto outputFile = mlir::openOutputFile(opt.outputFilename, &errorMessage);
  if (!outputFile) {
    llvm::WithColor::error()
        << "failed to open output file: " << errorMessage << "\n";
    return failure();
  }

  // Utility to call `process` with either the regular diagnostic handler, or,
  // if `--verify-diagnostics` is set, with the verifying handler.
  auto processBuffer = [&](std::unique_ptr<llvm::MemoryBuffer> buffer,
                           llvm::raw_ostream &os) -> LogicalResult {
    llvm::SourceMgr sourceMgr;
    sourceMgr.AddNewSourceBuffer(std::move(buffer), llvm::SMLoc());

    if (!opt.verifyDiagnostics) {
      mlir::SourceMgrDiagnosticHandler handler(sourceMgr, context);
      return process(context, sourceMgr, os);
    }

    mlir::SourceMgrDiagnosticVerifierHandler handler(sourceMgr, context);
    context->printOpOnDiagnostic(false);
    (void)process(context, sourceMgr, os);
    return handler.verify();
  };

  // Split the input file into chunks if the `--split-input-file` option is
  // set. Otherwise, process the entire input file as a single buffer.
  auto result = opt.splitInputFile
                    ? mlir::splitAndProcessBuffer(
                          std::move(inputFile), processBuffer, outputFile->os())
                    : processBuffer(std::move(inputFile), outputFile->os());

  // Keep the output file around if no errors occurred.
  if (succeeded(result))
    outputFile->keep();
  return result;
}

int main(int argc, char **argv) {
  // Register dialects and passes.
  mlir::DialectRegistry registry;
  silicon::registerAllDialects(registry);
  silicon::registerAllPasses();

  // Register pass manager command line options.
  mlir::registerAsmPrinterCLOptions();
  mlir::registerDefaultTimingManagerCLOptions();
  mlir::registerMLIRContextCLOptions();
  mlir::registerPassManagerCLOptions();

  // Parse command line options.
  cl::ParseCommandLineOptions(argc, argv,
                              "Silicon hardware description language compiler");

  // Perform the actual work.
  MLIRContext context(registry);
  context.printOpOnDiagnostic(false);
  exit(failed(executeCompiler(&context)));
}
