baseURL = "https://silicon-org.github.io/silicon/"
title = "Silicon"
theme = "hugo-book"
contentDir = "."

disableKinds = ["taxonomy"]
ignoreFiles = ['cmake_install\.cmake$', 'CMakeFiles']

[params]
BookSection = "/"

[markup.goldmark.renderer]
unsafe = true
