baseURL = "https://docs.silicon-lang.org/"
title = "Silicon"
theme = "hugo-book"
contentDir = "."

disableKinds = ["taxonomy"]
ignoreFiles = ['cmake_install\.cmake$', 'CMakeFiles']

[params]
BookSection = "/"   # include entire docs directory in navigation
BookTheme = "auto"  # switch between light and dark based on OS preferences

[markup.goldmark.renderer]
unsafe = true  # allow inline HTML and some other stuff

[markup.highlight]
style = "catppuccin-frappe"  # color theme for syntax highlighting

# Add the root `_index.md` file to the left sidebar.
[[menu.before]]
name = "Introduction"
pageRef = "/"
weight = 1

# Add a link to the GitHub repository to the left sidebar.
[[menu.after]]
name = "GitHub"
url = "https://github.com/silicon-org/silicon"
